name: diw
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - click
  - numpy==1.19.5
  - tensorflow-gpu==1.15
  - pip:
     - -e .  # install git checkout of diw in editable mode
     - tensorflow==1.15.0
     - tensorflow-graphics==1.0.0
     - absl-py>=0.5.0

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
