name: diw
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - click
  - numpy>=1.13.3
  - tensorflow-gpu==1.15
  - pip:
     - -e .  # install git checkout of diw in editable mode
     - tensorflow-graphics==1.0.0

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
